FROM ubuntu:21.04

RUN apt update && \
    apt install -y \
    libsdl1.2debian \
    libsdl-mixer1.2 \
    libglfw3 \
    libgcrypt20 \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    mesa-utils \
    alsa-utils \
    gstreamer1.0-plugins-good \
    gstreamer1.0-libav \
    libopengl0 \
    gdb \
    strace \
    libdwarf1
                                                      
WORKDIR /opt
