FROM ubuntu:23.10

RUN apt update && \
    apt install -y \
    libsdl1.2debian \
    libsdl-mixer1.2 \
    libglfw3 \
    libgcrypt20 \
    libgl1-mesa-dri \
    mesa-utils \
    alsa-utils \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-libav \
    libopengl0 \
    gdb \
    strace \
    libdwarf1 \
    wget \
    libglew2.2

RUN wget -O package.deb https://launchpad.net/ubuntu/+archive/primary/+files/libgl1-mesa-glx_23.0.4-0ubuntu1%7E22.04.1_amd64.deb && dpkg -i package.deb

WORKDIR /opt
